superpoint:
  module_path: "/home/liu/catkin_ws/src/visual_odometry/weight/superpoint.pt"
  conf_thresh: 0.1
  nn_thresh: 2
  nmx_box_size: 4
camera:
    #fx: 339.872425
    #fy: 340.441941
    #cx: 344.795123
    #cy: 195.057794
    #baseline: 0.12
    fx: 170.5
    fy: 170.5
    cx: 191.5
    cy: 103.4     
    baseline: 0.12
tracking:
  max_tracks: 5


